# Generated by Django 5.0.7 on 2024-07-14 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_alter_menuitem_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='owner_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='owner_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
